DemoSwiggy/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoSwiggy.Controllers
{
    public class CustomerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

DemoSwiggy/Controllers/SupportEngineersController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using DemoSwiggy.Interfaces;
using DemoSwiggy.Tools;
using DemoSwiggy.Models;
using DemoSwiggy.Repositories;
using Microsoft.EntityFrameworkCore;


namespace DemoSwiggy.Controllers
{
    public class SupportEngineersController : Controller
    {
        private readonly ISupportEmp _supportRepo;
        private readonly ILogger<SupportEngineersController> _logger;
        public SupportEngineersController(ISupportEmp supportRepo,ILogger<SupportEngineersController> logger)
        {
            _supportRepo = supportRepo;
            _logger = logger;
        }

        public IActionResult Index(string sortExpression = "", string SearchText = "", int pg = 1, int pageSize = 5)
        {
            SortModel sortModel = new SortModel();
            sortModel.AddColumn("name");
            sortModel.AddColumn("city");
            sortModel.ApplySort(sortExpression);
            ViewData["sortModel"] = sortModel;
            ViewBag.SearchText = SearchText;

            _logger.LogInformation($"Fetching the details from Index :: sortModel{sortModel} SearchText:{SearchText} SortExpression:{sortExpression}");

            PaginatedList<Customer> customer = _supportRepo.GetItems(sortModel.SortedProperty, sortModel.SortedOrder, SearchText, pg, pageSize);

            var pager = new PageModel(customer.TotalRecords, pg, pageSize);
            pager.SortExpression = sortExpression;
            this.ViewBag.Pager = pager;


            TempData["CurrentPage"]= pg;


            return View(customer);
        }
        public IActionResult Create()
        {
            Customer customer = new Customer();
            return View(customer);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Customer customer)
        {
            bool bolret = false;
            string errMessage = "";
            try
            {
                if (customer.Description.Length < 4 || customer.Description == null)
                {
                    errMessage = "Customer description must be atleast 4 characters";
                    
                }

                if (_supportRepo.IsCustomerNameExists(customer.Name)== true)
                {
                    errMessage = errMessage+""+"Customer Name "+customer.Name+" Exists Already";
                }
                if (errMessage == "")
                {
                    customer = _supportRepo.Create(customer);
                        bolret = true;
                }

                //customer = _supportRepo.Create(customer);
            }
            catch(Exception ex)
            {
                errMessage = errMessage + " " + ex.Message;
                _logger.LogError($"Exception Occurred :: {nameof(SupportEngineersController)}::{nameof(Create)}::{ex.Message}");
                
            }

            if (bolret == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(customer);
            }
            else 
            {
                TempData["SuccessMessage"] = "Customer " + customer.Name + " Created Successfully";
                return RedirectToAction(nameof(Index));
            }
            
        }
        public IActionResult Details(int id)
        {
            Customer customer = _supportRepo.GetCustomer(id);
            return View(customer);
        }
        public IActionResult Edit(int id)
        {
            Customer customer = _supportRepo.GetCustomer(id);
            return View(customer);
        }
        [HttpPost]
        public IActionResult Edit(Customer customer)
        {
            bool bolret = false;
            string errMessage = "";

            try
            {
                if (customer.Description.Length < 4 || customer.Description == null)
                    errMessage = "Customer description must be atleast 4 characters";

                if (_supportRepo.IsCustomerNameExists(customer.Name) == true)
                {
                    errMessage = errMessage + "" + "Customer Name " + customer.Name + " Exists Already";
                }
                if (errMessage == "")
                {
                    customer = _supportRepo.Edit(customer);
                    bolret = true;
                }

            }
            catch(Exception ex)
            {
                errMessage = errMessage + " " + ex.Message;
                _logger.LogError($"Exception Occurred :: {nameof(SupportEngineersController)}::{nameof(Edit)}::{ex.Message}");

            }


            TempData["SuccessMessage"] = "Customer "+ customer.Name + " Saved Successfully";

            int CurrentPage = 1;
            if (TempData["CurrentPage"] != null)
                CurrentPage = (int)TempData["CurrentPage"];


            if (bolret == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(customer);
            }
            else
            {
                TempData["SuccessMessage"] = "Customer " + customer.Name + " Created Successfully";
                return RedirectToAction(nameof(Index));
            }


            return RedirectToAction(nameof(Index),new { pg=CurrentPage});
        }
        public IActionResult Delete(int id)
        {
            Customer customer = _supportRepo.GetCustomer(id);
            return View(customer);
        }

        [HttpPost]
        public IActionResult Delete(Customer customer)
        {
            try
            {
                customer = _supportRepo.Delete(customer);
            }
            catch(Exception ex)
            {
                _logger.LogError($"Exception Occurred :: {nameof(SupportEngineersController)}::{nameof(Delete)}::{ex.Message}");
            }

            TempData["SuccessMessage"] = "Customer "+customer.Name + " Deleted Successfully";
            int CurrentPage = 1;
            if (TempData["CurrentPage"] != null)
                CurrentPage = (int)TempData["CurrentPage"];


            return RedirectToAction(nameof(Index), new { pg = CurrentPage });
        }
    }
    
}

DemoSwiggy/Views/Shared/_Layout.cshtml
<<<<<<< HEAD
﻿
 <!DOCTYPE html>
=======
﻿@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
>>>>>>> 0c9e4de8396db560b307968b31232fd6cf9e306c
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoSwiggy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoSwiggy</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if(SignInManager.IsSignedIn(User))
                        { 
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SupportEngineers" asp-action="Index">Support Employee</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <!-----Success Dialogue Start----->
            <div id="myModalSuccess" class="modal fade text-width:30%;" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h2>Information</h2>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div id="MyModalSuccessAlertBody" class="modal-body alert alert-sucess">
                            this is a modal body.our message willl appear here
                        </div>
                        <div class="modal-footer">
                            &nbsp;
                            <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-----Success Dialogue End----->
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DemoSwiggy - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DemoSwiggy/Views/Shared/_bottomBar.cshtml
@model PageModel

<div class="container m-0 p-0 btn-group" style="background-color:black; border-radius:10px;height:45px;color:white;">

    <div class="col-4 btn-group p-1 m-1">
        <p>
            Showing @Model.StartRecord to @Model.EndRecord of @Model.TotalItems Rows
        </p>
    </div>

    <div class="col-3 btn-group justify-content-end">
        <span class="col-7 mt-2 p-0"> Rows Per Page  </span>

        <span class="col-5 p-1">
            <select class="form-control" id="pageSelector" asp-items="Model.GetPageSizes();"
                    onchange="ChangePageSize(this);">
            </select>
        </span>
    </div>

    <div class="col-4 btn-group justify-content-end mt-1">
        <p>
            Showing @Model.CurrentPage / @Model.TotalPages Rows
        </p>
    </div>
</div>
<script>
    function ChangePageSize(obj) {
        var controllerName = "@this.ViewContext.RouteData.Values["controller"].ToString()";
        window.location.href = "/" + controllerName + "/@Model.Action" + "?pageSize=" + obj.value + "&SearchText@Model.SearchText" + "&sortExpression=" + "@Model.SortExpression";
    }
</script>

DemoSwiggy/Views/Shared/_topBar.cshtml
@model PageModel
<style>
    .page-link {
        color: black !important;
    }

    .page-item.active .page-link {
        z-index: 3;
        color: #fff;
        background-color: red !important;
        border-color: red;
    }
</style>
<div class="container btn-group" style="background-color:black; border-radius:10px;height:45px;">

    <div class="col-4 p-0 justify-content-end mt-1">
        <form asp-action="index">
            <span class="btn-group">
                <input class="form-control" type="text"
                       name="SearchText" value="@ViewBag.SearchText" placeholder="Search Key" />

                <span class="m1-2 btn-group btn-danger" style="border-radius:10px;">
                    <i class="p1-2 fade fa-search align-self-senter" arial-hidden="true"></i>
                    <input class="btn btn-sm font-weight-bold text-white" style="border-radius: 10px; margin-left: 10px"
                           type="submit" value="Search" />
                </span>
            </span>

        </form>
    </div>
    <div class="container mt-1">
        <ul class="pagination justify-content-end">
            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="@Model.Action"
                       asp-route-pg="1" asp-route-pageSize="@Model.PageSize"
                       asp-route-SearchText="@Model.SearchText"
                       asp-route-sortExpression="@Model.SortExpression">
                        First
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-action="@Model.Action"
                       asp-route-pg="@(Model.CurrentPage-1)"
                       asp-route-pageSize="@Model.PageSize"
                       asp-route-SearchText="@Model.SearchText"
                       asp-route-sortExpression="@Model.SortExpression">
                        Previous
                    </a>
                </li>
            }
            @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
            {
                <li class="page-item @(pge==Model.CurrentPage ?"active" : "")">
                    @if (pge != Model.CurrentPage)
                    {
                        <a class="page-link" asp-action="@Model.Action"
                           asp-route-pg="@pge"
                           asp-route-pageSize="@Model.PageSize"
                           asp-route-SearchText="@Model.SearchText"
                           asp-route-sortExpression="@Model.SortExpression">
                            @pge
                        </a>
                    }
                    else
                    {
                        <span class="page-link">@pge</span>
                    }
                </li>
            }
            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="@Model.Action"
                       asp-route-pg="@(Model.CurrentPage+1)" asp-route-pageSize="@Model.PageSize"
                       asp-route-SearchText="@Model.SearchText"
                       asp-route-sortExpression="@Model.SortExpression">
                        Next
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-action="@Model.Action"
                       asp-route-pg="@(Model.TotalPages)" asp-route-pageSize="@Model.PageSize"
                       asp-route-SearchText="@Model.SearchText"
                       asp-route-sortExpression="@Model.SortExpression">
                        Last
                    </a>
                </li>
            }
        </ul>
    </div>
</div>